name: rethinkdb_driver
version: 2.3.2+1
author: William Welch <billywelch@gmail.com>
description: Dart driver for RethinkDB.
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
environment:
  sdk: ">=1.13.0 <2.0.0"
dependencies:
  protobuf: "^0.5.5"
  crypto: "^2.0.2+1"
  convert: "^2.0.1"
  pbkdf2: "^0.2.0"
dev_dependencies:
  test: "^0.12.24+8"
