name: rethinkdb_driver
version: 2.3.2+2
author: William Welch <billywelch@gmail.com>
description: Dart driver for RethinkDB.
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
environment:
  sdk: ">=1.20.0 <3.0.0"
dependencies:
  protobuf: "^0.10.2"
  crypto: "^2.0.6"
  convert: "^2.0.2"
  pbkdf2: 
    git: "https://github.com/jamesots/pbkdf2"
dev_dependencies:
  test: "^1.3.0"
